version: '3'
services:
  php:
    image: php:8.2-apache
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=php
      - MYSQL_USER=team_seven
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      #- ./db:docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8030:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

